export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";
export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";

export const FETCH_PRODUCT_DETAIL_ERROR = "FETCH_PRODUCT_DETAIL_ERROR";
export const FETCH_PRODUCT_DETAIL_REQUEST = "FETCH_PRODUCT_DETAIL_REQUEST";
export const FETCH_PRODUCT_DETAIL_SUCCESS = "FETCH_PRODUCT_DETAIL_SUCCESS";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const ADD_PRODUCT_TO_CART_REQUEST = "ADD_PRODUCT_TO_CART_REQUEST";
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_ERROR = "ADD_PRODUCT_TO_CART_ERROR";

export const FETCH_ITEM_CART_REQUEST = "FETCH_ITEM_CART_REQUEST";
export const FETCH_ITEM_CART_SUCCESS = "FETCH_ITEM_CART_SUCCESS";
export const FETCH_ITEM_CART_ERROR = "FETCH_ITEM_CART_ERROR";

export const SET_CART_ETAG = "SET_CART_ETAG";

export const DELETE_PRODUCT_CART_SUCCESS = "DELETE_PRODUCT_CART_SUCCESS";
