export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";
export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";

export const FETCH_PRODUCT_DETAIL_ERROR = "FETCH_PRODUCT_DETAIL_ERROR";
export const FETCH_PRODUCT_DETAIL_REQUEST = "FETCH_PRODUCT_DETAIL_REQUEST";
export const FETCH_PRODUCT_DETAIL_SUCCESS = "FETCH_PRODUCT_DETAIL_SUCCESS";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_ERORR = "FETCH_USER_ERORR";

export const UPDATE_ACCOUNT_REQUEST = "UPDATE_ACCOUNT_REQUEST";
export const UPDATE_ACCOUNT_SUCCESS = "UPDATE_ACCOUNT_SUCCESS";
export const UPDATE_ACCOUNT_ERROR = "UPDATE_ACCOUNT_ERROR";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const ADD_PRODUCT_TO_CART_REQUEST = "ADD_PRODUCT_TO_CART_REQUEST";
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_ERROR = "ADD_PRODUCT_TO_CART_ERROR";

export const UPDATE_PRODUCT_CART_REQUEST = "UPDATE_PRODUCT_CART_REQUEST";
export const UPDATE_PRODUCT_CART_SUCCESS = "UPDATE_PRODUCT_CART_SUCCESS";
export const UPDATE_PRODUCT_CART_ERROR = "UPDATE_PRODUCT_CART_ERROR";

export const FETCH_ITEM_CART_REQUEST = "FETCH_ITEM_CART_REQUEST";
export const FETCH_ITEM_CART_SUCCESS = "FETCH_ITEM_CART_SUCCESS";
export const FETCH_ITEM_CART_ERROR = "FETCH_ITEM_CART_ERROR";

export const DEFAULT_CART = "DEFAULT_CART";

export const DELETE_PRODUCT_CART_SUCCESS = "DELETE_PRODUCT_CART_SUCCESS";

export const DELETE_ALL_PRODUCT_CART_SUCCESS =
  "DELETE_ALL_PRODUCT_CART_SUCCESS";

export const ADD_ORDER_REQUEST = "ADD_ORDER_REQUEST";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_ERROR = "ADD_ORDER_ERROR";

export const FETCH_ORDER_BY_ID_REQUEST = "FETCH_ORDER_BY_ID_REQUEST";
export const FETCH_ORDER_BY_ID_SUCCESS = "FETCH_ORDER_BY_ID_SUCCESS";
export const FETCH_ORDER_BY_ID_ERROR = "FETCH_ORDER_BY_ID_ERROR";

export const FETCH_ORDER_DETAILS_REQUEST = "FETCH_ORDER_DETAILS_REQUEST";
export const FETCH_ORDER_DETAILS_SUCCESS = "FETCH_ORDER_DETAILS_SUCCESS";
export const FETCH_ORDER_DETAILS_ERROR = "FETCH_ORDER_DETAILS_ERROR";

export const ADD_PRODUCT_TO_WISHLIST_REQUEST =
  "ADD_PRODUCT_TO_WISHLIST_REQUEST";
export const ADD_PRODUCT_TO_WISHLIST_SUCCESS =
  "ADD_PRODUCT_TO_WISHLIST_SUCCESS";
export const ADD_PRODUCT_TO_WISHLIST_ERROR = "ADD_PRODUCT_TO_WISHLIST_ERROR";

export const FETCH_ITEM_WISHLIST_REQUEST = "FETCH_ITEM_WISHLIST_REQUEST";
export const FETCH_ITEM_WISHLIST_SUCCESS = "FETCH_ITEM_WISHLIST_SUCCESS";
export const FETCH_ITEM_WISHLIST_ERROR = "FETCH_ITEM_WISHLIST_ERROR";

export const DELETE_PRODUCT_WISHLIST_SUCCESS =
  "DELETE_PRODUCT_WISHLIST_SUCCESS";

export const FETCH_BLOG_REQUEST = "FETCH_BLOG_REQUEST";
export const FETCH_BLOG_SUCCESS = "FETCH_BLOG_SUCCESS";
export const FETCH_BLOG_ERROR = "FETCH_BLOG_ERROR";

export const FETCH_ADDRESS_REQUEST = "FETCH_ADDRESS_REQUEST";
export const FETCH_ADDRESS_SUCCESS = "FETCH_ADDRESS_SUCCESS";
export const FETCH_ADDRESS_ERROR = "FETCH_ADDRESS_ERROR";

export const FETCH_BLOG_DETAIL_ERROR = "FETCH_BLOG_DETAIL_ERROR";
export const FETCH_BLOG_DETAIL_REQUEST = "FETCH_BLOG_DETAIL_REQUEST";
export const FETCH_BLOG_DETAIL_SUCCESS = "FETCH_BLOG_DETAIL_SUCCESS";

export const SET_ACTIVE = "SET_ACTIVE";

// export const FETCH_REVIEW_BY_PRODUCT_REQUEST =
//   "FETCH_REVIEW_BY_PRODUCT_REQUEST";
// export const FETCH_REVIEW_BY_PRODUCT_SUCCESS =
//   "FETCH_REVIEW_BY_PRODUCT_SUCCESS";
// export const FETCH_REVIEW_BY_PRODUCT_ERROR = "FETCH_REVIEW_BY_PRODUCT_ERROR";
